name: 512HP
favicon: null
layout_spectrum: 0.4313509319908917
typography_spectrum: 0.2054400979541242
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9257998736575246
  lightness: 0.13688372843898833
  saturation: 0.30810470157302916
  rhythmicContrast: 0.7705801604315639
purpose: []
