name: 512HP
favicon: null
layout_spectrum: 0
typography_spectrum: 0.50775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#cbd9e4'
    - '#7b746e'
    - '#4b4341'
    - '#b7900c'
  brandStrength: 0.9257998736575246
  lightness: 0.13688372843898833
  saturation: 0.30810470157302916
  rhythmicContrast: 0.7705801604315639
purpose: []
